# Generated by Django 5.1.5 on 2025-02-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_students_created_at_alter_students_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
