# Generated by Django 5.1.5 on 2025-02-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendances_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
